/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1;

/**
 *
 * @author Adity
 */
public class Tugas10 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas10
     */
    public Tugas10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        eHasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eP = new javax.swing.JTextField();
        eL = new javax.swing.JTextField();
        eT = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        menProses = new javax.swing.JMenu();
        meltBersih = new javax.swing.JMenuItem();
        menHitung = new javax.swing.JMenu();
        meltKali = new javax.swing.JMenuItem();
        meltBagi = new javax.swing.JMenuItem();
        meltTambah = new javax.swing.JMenuItem();
        meltKurang = new javax.swing.JMenuItem();
        menRumus = new javax.swing.JMenu();
        meltSegitiga = new javax.swing.JMenuItem();
        meltPP = new javax.swing.JMenuItem();
        meltLingkaran = new javax.swing.JMenuItem();
        menBantuan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eData2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data 1");

        jLabel2.setText("Data 2");

        jLabel3.setText("Hasil");

        jLabel4.setText("Panjang ");

        jLabel5.setText("Lebar");

        jLabel6.setText("Tinggi & R");

        eP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePActionPerformed(evt);
            }
        });

        menFile.setText("File");
        jMenuBar1.add(menFile);

        menProses.setText("Proses");

        meltBersih.setText("Bersih");
        menProses.add(meltBersih);

        menHitung.setText("Hitung");

        meltKali.setText("Kali");
        meltKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKaliActionPerformed(evt);
            }
        });
        menHitung.add(meltKali);

        meltBagi.setText("Bagi");
        meltBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltBagiActionPerformed(evt);
            }
        });
        menHitung.add(meltBagi);

        meltTambah.setText("Tambah");
        meltTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltTambahActionPerformed(evt);
            }
        });
        menHitung.add(meltTambah);

        meltKurang.setText("Kurang");
        meltKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKurangActionPerformed(evt);
            }
        });
        menHitung.add(meltKurang);

        menProses.add(menHitung);

        menRumus.setText("Rumus");

        meltSegitiga.setText("Segitiga");
        meltSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltSegitigaActionPerformed(evt);
            }
        });
        menRumus.add(meltSegitiga);

        meltPP.setText("Persegi Panjang");
        meltPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltPPActionPerformed(evt);
            }
        });
        menRumus.add(meltPP);

        meltLingkaran.setText("Lingkaran");
        meltLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLingkaranActionPerformed(evt);
            }
        });
        menRumus.add(meltLingkaran);

        menProses.add(menRumus);

        jMenuBar1.add(menProses);

        menBantuan.setText("Bantuan");
        jMenuBar1.add(menBantuan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eHasil))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eT, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eL, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(eT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meltBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltBagiActionPerformed
    int Data1 = eData1.getText().isEmpty() ? 0 : Integer.parseInt(eData1.getText());
    int Data2 = eData2.getText().isEmpty() ? 1 : Integer.parseInt(eData2.getText()); // Avoid division by zero
    int Hasil = Data1 / Data2; 
    eHasil.setText(String.valueOf(Hasil));
        // TODO add your handling code here:
    }//GEN-LAST:event_meltBagiActionPerformed

    private void eData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eData2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eData2ActionPerformed

    private void meltKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKaliActionPerformed
    int Data1 = eData1.getText().isEmpty() ? 0 : Integer.parseInt(eData1.getText());
    int Data2 = eData2.getText().isEmpty() ? 0 : Integer.parseInt(eData2.getText());
    int Hasil = Data1 * Data2; 
    eHasil.setText(String.valueOf(Hasil)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_meltKaliActionPerformed

    private void meltTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltTambahActionPerformed
        int Data1 = eData1.getText().isEmpty() ? 0 : Integer.parseInt(eData1.getText());
        int Data2 = eData2.getText().isEmpty() ? 0 : Integer.parseInt(eData2.getText());
        int Hasil = Data1 + Data2; 
        eHasil.setText(String.valueOf(Hasil));
    }//GEN-LAST:event_meltTambahActionPerformed

    private void meltKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKurangActionPerformed
        int Data1 = eData1.getText().isEmpty() ? 0 : Integer.parseInt(eData1.getText());
        int Data2 = eData2.getText().isEmpty() ? 0 : Integer.parseInt(eData2.getText());
        int Hasil = Data1 - Data2; 
        eHasil.setText(String.valueOf(Hasil));
        // TODO add your handling code here:
    }//GEN-LAST:event_meltKurangActionPerformed

    private void ePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePActionPerformed

    private void meltPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltPPActionPerformed
    int Panjang = eP.getText().isEmpty() ? 0 : Integer.parseInt(eP.getText());
    int Lebar = eL.getText().isEmpty() ? 0 : Integer.parseInt(eL.getText());
    int Luas = Panjang * Lebar;
    int Keliling = 2 * (Panjang + Lebar);
    eHasil.setText("Luas = " + Luas + ", Keliling = " + Keliling);
    }//GEN-LAST:event_meltPPActionPerformed

    private void meltLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLingkaranActionPerformed
    int Radius = eT.getText().isEmpty() ? 0 : Integer.parseInt(eT.getText());
    int Luas = (int) (Math.PI * Radius * Radius);
    int Keliling = (int) (2 * Math.PI * Radius);
    eHasil.setText("Luas = " + Luas + ", Keliling = " + Keliling);
    }//GEN-LAST:event_meltLingkaranActionPerformed

    private void meltSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltSegitigaActionPerformed
    int Alas = eP.getText().isEmpty() ? 0 : Integer.parseInt(eP.getText());
    int Tinggi = eL.getText().isEmpty() ? 0 : Integer.parseInt(eL.getText());
    int SisiMiring = eT.getText().isEmpty() ? 0 : Integer.parseInt(eT.getText());
    int Luas = (Alas * Tinggi) / 2;
    int Keliling = Alas + Tinggi + SisiMiring;
    eHasil.setText("Luas = " + Luas + ", Keliling = " + Keliling);
    }//GEN-LAST:event_meltSegitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eHasil;
    private javax.swing.JTextField eL;
    private javax.swing.JTextField eP;
    private javax.swing.JTextField eT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meltBagi;
    private javax.swing.JMenuItem meltBersih;
    private javax.swing.JMenuItem meltKali;
    private javax.swing.JMenuItem meltKurang;
    private javax.swing.JMenuItem meltLingkaran;
    private javax.swing.JMenuItem meltPP;
    private javax.swing.JMenuItem meltSegitiga;
    private javax.swing.JMenuItem meltTambah;
    private javax.swing.JMenu menBantuan;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menHitung;
    private javax.swing.JMenu menProses;
    private javax.swing.JMenu menRumus;
    // End of variables declaration//GEN-END:variables
}
