/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1;

import javax.swing.DefaultListModel;

/**
 *
 * @author Adity
 */
public class Tugas7 extends javax.swing.JFrame {

    /**
     * Creates new form Tugas7
     */
    public Tugas7() {
        initComponents();
        ListModel = new DefaultListModel(); // Yang perlu
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AreaKota = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListMinuman = new javax.swing.JList<>();
        cMakanan = new javax.swing.JComboBox<>();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bSisip = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        eUbah = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(AreaKota);

        jScrollPane2.setViewportView(ListMinuman);

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bSisip.setText("Sisip");
        bSisip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSisipActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(eUbah);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bHapus)
                            .addComponent(bUbah)
                            .addComponent(bSisip)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bTambah)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(bTambah))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSisip)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        javax.swing.text.Document doc = AreaKota.getDocument();
    
    try {
        // Get the text from the document
        String text = doc.getText(0, doc.getLength());
        int endIndex = text.indexOf("\n");
        
        if (endIndex != -1) {
            // Remove the text up to the first newline
            doc.remove(0, endIndex + 1);
        } else {
            // Remove all text if no newline is found
            doc.remove(0, doc.getLength());
        }
    } catch (javax.swing.text.BadLocationException e) {
        e.printStackTrace(); // Handle the exception
    }

    // Remove first item from JComboBox
    if (cMakanan.getItemCount() > 0) { 
        cMakanan.removeItemAt(0);
    }

    // Remove first item from ListModel
    if (ListModel.getSize() > 0) { 
        ListModel.remove(0);
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        AreaKota.setText(AreaKota.getText() + "Gersik\n");
        AreaKota.setText(AreaKota.getText() + "Malang\n");
        AreaKota.setText(AreaKota.getText() + "Surabaya\n");

        cMakanan.insertItemAt("Rujak", 0); 
        cMakanan.insertItemAt("Rawon", 1); 
        cMakanan.insertItemAt("Sate", 2); 

        ListModel.add(0, "Sprite"); 
        ListModel.add(1, "Fanta"); 
        ListModel.add(2, "Es Batu"); 
        ListModel.add(3, "Kopi"); 
        ListMinuman.setModel(ListModel); 
    }//GEN-LAST:event_bTambahActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
        try {
        // Get the Document from JTextPane
        javax.swing.text.Document doc = AreaKota.getDocument();
        
        // Define start and end indices
        int start = 0;
        int end = doc.getLength(); // Assuming you want to replace the entire content
        
        // Remove the text from the document
        doc.remove(start, end - start);
        
        // Insert the new text
        doc.insertString(start, eUbah.getText() + "\n", null);
    } catch (javax.swing.text.BadLocationException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bSisipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSisipActionPerformed
        // TODO add your handling code here:
            try {
        javax.swing.text.Document doc = AreaKota.getDocument();
        doc.insertString(doc.getLength(), "Lamongan\n", null); // Append "Lamongan" at the end
    } catch (javax.swing.text.BadLocationException e) {
        e.printStackTrace(); // Handle the exception
    }

    // Insert text at the beginning
    try {
        javax.swing.text.Document doc = AreaKota.getDocument();
        doc.insertString(0, "Kab.\n", null); // Insert "Kab." at the beginning
    } catch (javax.swing.text.BadLocationException e) {
        e.printStackTrace(); // Handle the exception
    }

    // Adding items to JComboBox
    cMakanan.insertItemAt("Soto", 3); // Insert "Soto" at index 3
    cMakanan.insertItemAt("Pecel", 0); // Insert "Pecel" at index 0

    // Adding items to DefaultListModel
    ListModel.insertElementAt("Jus Apokat", 4); // Insert "Jus Apokat" at index 4
    ListModel.insertElementAt("Jus Tomat", 5); // Insert "Jus Tomat" at index 5
    }//GEN-LAST:event_bSisipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
           java.awt.EventQueue.invokeLater(() -> new Tugas7().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AreaKota;
    private javax.swing.JList<String> ListMinuman;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSisip;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JComboBox<String> cMakanan;
    private javax.swing.JTextPane eUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
    DefaultListModel ListModel;
}
